os: linux
install: sudo apt-get install nasm xorriso grub-pc-bin qemu-kvm qemu virt-manager virt-viewer libvirt-bin

language: c

sudo: false

before_script:
  - mkdir -p build/{io,libk,x86}
  - mkdir -p iso/boot/grub

script:
  - make iso
